/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author rkhan
 */
public class FeesStatus extends javax.swing.JFrame {

    public FeesStatus() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        getContentPane().setBackground(new Color(255, 255, 255));
        PromptSupport.setPrompt("Enter student's GR number", std_gr);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fee = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        std_gr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dec1 = new javax.swing.JComboBox<>();
        jan1 = new javax.swing.JComboBox<>();
        feb1 = new javax.swing.JComboBox<>();
        march1 = new javax.swing.JComboBox<>();
        april1 = new javax.swing.JComboBox<>();
        may1 = new javax.swing.JComboBox<>();
        june1 = new javax.swing.JComboBox<>();
        july1 = new javax.swing.JComboBox<>();
        aug1 = new javax.swing.JComboBox<>();
        sep1 = new javax.swing.JComboBox<>();
        oct1 = new javax.swing.JComboBox<>();
        nov1 = new javax.swing.JComboBox<>();
        pdec = new javax.swing.JTextField();
        pjan = new javax.swing.JTextField();
        pfeb = new javax.swing.JTextField();
        pmarch = new javax.swing.JTextField();
        papril = new javax.swing.JTextField();
        pmay = new javax.swing.JTextField();
        pjune = new javax.swing.JTextField();
        pjuly = new javax.swing.JTextField();
        paug = new javax.swing.JTextField();
        psep = new javax.swing.JTextField();
        poct = new javax.swing.JTextField();
        pnov = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ddec = new javax.swing.JTextField();
        djan = new javax.swing.JTextField();
        dfeb = new javax.swing.JTextField();
        dmarch = new javax.swing.JTextField();
        dapril = new javax.swing.JTextField();
        dmay = new javax.swing.JTextField();
        djune = new javax.swing.JTextField();
        djuly = new javax.swing.JTextField();
        daug = new javax.swing.JTextField();
        dsep = new javax.swing.JTextField();
        doct = new javax.swing.JTextField();
        dnov = new javax.swing.JTextField();

        fee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        fee.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_gr.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        std_gr.setForeground(new java.awt.Color(0, 196, 75));
        std_gr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 196, 75), 1, true));
        std_gr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                std_grKeyPressed(evt);
            }
        });
        getContentPane().add(std_gr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 330, 30));

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 196, 75));
        jLabel2.setText("Student's GR Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_22px_1.png"))); // NOI18N
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 40, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 196, 75), 2));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 196, 75));
        jLabel3.setText("Update");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 120, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 196, 75));
        jLabel1.setText("December");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 196, 75));
        jLabel5.setText("January");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 196, 75));
        jLabel6.setText("February");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 196, 75));
        jLabel7.setText("March");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 196, 75));
        jLabel8.setText("April");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 196, 75));
        jLabel9.setText("May");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 196, 75));
        jLabel10.setText("June");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 196, 75));
        jLabel11.setText("July");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 196, 75));
        jLabel12.setText("August");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 196, 75));
        jLabel13.setText("September");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 196, 75));
        jLabel14.setText("October");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 196, 75));
        jLabel15.setText("November");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, -1));

        dec1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dec1.setForeground(new java.awt.Color(0, 196, 75));
        dec1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(dec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        jan1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jan1.setForeground(new java.awt.Color(0, 196, 75));
        jan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(jan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        feb1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        feb1.setForeground(new java.awt.Color(0, 196, 75));
        feb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(feb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        march1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        march1.setForeground(new java.awt.Color(0, 196, 75));
        march1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(march1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        april1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        april1.setForeground(new java.awt.Color(0, 196, 75));
        april1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(april1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        may1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        may1.setForeground(new java.awt.Color(0, 196, 75));
        may1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(may1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        june1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        june1.setForeground(new java.awt.Color(0, 196, 75));
        june1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(june1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        july1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        july1.setForeground(new java.awt.Color(0, 196, 75));
        july1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(july1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        aug1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        aug1.setForeground(new java.awt.Color(0, 196, 75));
        aug1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(aug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        sep1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sep1.setForeground(new java.awt.Color(0, 196, 75));
        sep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        oct1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        oct1.setForeground(new java.awt.Color(0, 196, 75));
        oct1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(oct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        nov1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nov1.setForeground(new java.awt.Color(0, 196, 75));
        nov1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Paid", "Paid" }));
        getContentPane().add(nov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        pdec.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pdec.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pdec, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 200, 20));

        pjan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pjan.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pjan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 200, 20));

        pfeb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pfeb.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pfeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 200, 20));

        pmarch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pmarch.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pmarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 200, 20));

        papril.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        papril.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(papril, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 200, 20));

        pmay.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pmay.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pmay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 200, 20));

        pjune.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pjune.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pjune, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 200, 20));

        pjuly.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pjuly.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pjuly, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 200, 20));

        paug.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        paug.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(paug, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 20));

        psep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        psep.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(psep, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 200, 20));

        poct.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poct.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(poct, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 200, 20));

        pnov.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnov.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(pnov, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 200, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(1, 80, 48));
        jLabel16.setText("Months");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(1, 80, 48));
        jLabel17.setText("Date");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(1, 80, 48));
        jLabel18.setText("Pay Order/Cheque Number");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(1, 80, 48));
        jLabel19.setText("Status");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 196, 75));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 430, 30));

        ddec.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ddec.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(ddec, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 130, 20));

        djan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        djan.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(djan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 130, 20));

        dfeb.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dfeb.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dfeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 130, 20));

        dmarch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dmarch.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dmarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 130, 20));

        dapril.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dapril.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dapril, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 130, 20));

        dmay.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dmay.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dmay, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 130, 20));

        djune.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        djune.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(djune, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 20));

        djuly.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        djuly.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(djuly, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 130, 20));

        daug.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        daug.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(daug, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 130, 20));

        dsep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dsep.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dsep, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 130, 20));

        doct.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        doct.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(doct, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 130, 20));

        dnov.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dnov.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(dnov, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 130, 20));

        setSize(new java.awt.Dimension(712, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        getFee();
        getNum();
        getTime();
    }//GEN-LAST:event_searchMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        setTime();
        setFee();
        setNum();
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void std_grKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_grKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getFee();
            getNum();
            getTime();
        }
    }//GEN-LAST:event_std_grKeyPressed

    public void getFee() {
        try {
            String qry = "Select * from fee_status where std_gr='" + std_gr.getText() + "'";
            ResultSet rs = DatabaseConnection.getData(qry);
            
            if (rs.next()) {
                try {
                    System.out.println(rs.getString("jan"));
                    String name = rs.getString("std_name");
                    System.out.println(rs.getString("jan"));
                    String jan = rs.getString("jan");
                    String feb = rs.getString("feb");
                    String march = rs.getString("march");
                    String april = rs.getString("april");
                    String may = rs.getString("may");
                    String june = rs.getString("june");
                    String july = rs.getString("july");
                    String aug = rs.getString("aug");
                    String sep = rs.getString("sep");
                    String oct = rs.getString("oct");
                    String nov = rs.getString("nov");
                    String dec = rs.getString("decc");
                    jLabel4.setText(name);

                    checkstatus(jan, jan1);
                    checkstatus(feb, feb1);
                    checkstatus(march, march1);
                    checkstatus(april, april1);
                    checkstatus(may, may1);
                    checkstatus(june, june1);
                    checkstatus(july, july1);
                    checkstatus(aug, aug1);
                    checkstatus(sep, sep1);
                    checkstatus(oct, oct1);
                    checkstatus(nov, nov1);
                    checkstatus(dec, dec1);

                } catch (SQLException ex) {
                    Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }

    public void getNum() {
        String qry = "Select * from pay_order where std_gr='" + std_gr.getText() + "'";
        try {
            ResultSet rs = DatabaseConnection.getData(qry);
            while (rs.next()) {
                pjan.setText(rs.getString("jan"));
                pfeb.setText(rs.getString("feb"));
                pmarch.setText(rs.getString("march"));
                papril.setText(rs.getString("april"));
                pmay.setText(rs.getString("may"));
                pjune.setText(rs.getString("june"));
                pjuly.setText(rs.getString("july"));
                paug.setText(rs.getString("aug"));
                psep.setText(rs.getString("sep"));
                poct.setText(rs.getString("oct"));
                pnov.setText(rs.getString("nov"));
                pdec.setText(rs.getString("decc"));
            }

        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void getTime() {
        String qry = "select * from timestamp where std_gr='" + std_gr.getText() + "'";
        try {
            ResultSet rs = DatabaseConnection.getData(qry);
            while (rs.next()) {
                String tjan = rs.getString("jan");
                djan.setText(tjan);
                String tfeb = rs.getString("feb");
                dfeb.setText(tfeb);
                String tmarch = rs.getString("march");
                dmarch.setText(tmarch);
                String tapril = rs.getString("april");
                dapril.setText(tapril);
                String tmay = rs.getString("may");
                dmay.setText(tmay);
                String tjune = rs.getString("june");
                djune.setText(tjune);
                String tjuly = rs.getString("july");
                djuly.setText(tjuly);
                String taug = rs.getString("aug");
                daug.setText(taug);
                String tsep = rs.getString("sep");
                dsep.setText(tsep);
                String toct = rs.getString("oct");
                doct.setText(toct);
                String tnov = rs.getString("nov");
                dnov.setText(tnov);
                String tdec = rs.getString("decc");
                ddec.setText(tdec);

            }
        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFee() {
        String jan = (String) jan1.getSelectedItem();
        String feb = (String) feb1.getSelectedItem();
        String march = (String) march1.getSelectedItem();
        String april = (String) april1.getSelectedItem();
        String may = (String) may1.getSelectedItem();
        String june = (String) june1.getSelectedItem();
        String july = (String) july1.getSelectedItem();
        String aug = (String) aug1.getSelectedItem();
        String sep = (String) sep1.getSelectedItem();
        String oct = (String) oct1.getSelectedItem();
        String nov = (String) nov1.getSelectedItem();
        String dec = (String) dec1.getSelectedItem();

        try {

            int a = DatabaseConnection.setData("update fee_status set jan='" + jan + "',feb='" + feb + "',march='" + march + "',april='" + april + "',may='" + may + "',june='" + june + "',july='" + july + "',aug='" + aug + "',sep='" + sep + "',oct='" + oct + "',nov='" + nov + "',decc='" + dec + "' where std_gr='" + std_gr.getText() + "'");
            if (a > 0) {
                StartGUI.displayMessage("Updated Successfully.");
                clearText();
            } else {
                StartGUI.displayMessage("Updation Failed.");
            }
        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setNum() {

        String njan1 = pjan.getText();
        String nfeb1 = pfeb.getText();
        String nmarch1 = pmarch.getText();
        String napril1 = papril.getText();
        String nmay1 = pmay.getText();
        String njune1 = pjune.getText();
        String njuly1 = pjuly.getText();
        String naug1 = paug.getText();
        String nsep1 = psep.getText();
        String noct1 = poct.getText();
        String nnov1 = pnov.getText();
        String ndec1 = pdec.getText();

        try {
            DatabaseConnection.setData("update pay_order set jan='" + njan1 + "',feb='" + nfeb1 + "',march='" + nmarch1 + "',april='" + napril1 + "',may='" + nmay1 + "',june='" + njune1 + "',july='" + njuly1 + "',aug='" + naug1 + "',sep='" + nsep1 + "',oct='" + noct1 + "',nov='" + nnov1 + "',decc='" + ndec1 + "' where std_gr='" + std_gr.getText() + "'");
        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setTime() {
        try {
        SimpleDateFormat ab = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        
        String jy = djan.getText();
        String fy = dfeb.getText();
        String mh = dmarch.getText();
        String al = dapril.getText();
        String my = dmay.getText();
        String je = djune.getText();
        String july = djuly.getText();
        String at = daug.getText();
        String sr = dsep.getText();
        String or = doct.getText();
        String nr = dnov.getText();
        String dr = ddec.getText();
        
        if(jy.equals("")){
            djan.setText("0");
        }else if(fy.equals("")){
            dfeb.setText("0");
        }else if(mh.equals("")){
            dmarch.setText("0");
        }else if(al.equals("")){
            dapril.setText("0");
        }else if(my.equals("")){
            dmay.setText("0");
        }else if(je.equals("")){
            dmay.setText("0");
        }else if(july.equals("")){
            djuly.setText("0");
        }else if(at.equals("")){
            daug.setText("0");
        }else if(sr.equals("")){
            dsep.setText("0");
        }else if(or.equals("")){
            doct.setText("0");
        }else if(nr.equals("")){
            dnov.setText("");
        }else if(dr.equals("")){
            ddec.setText("0");
        }
        
        DatabaseConnection.setData("update timestamp set jan= '"+jy+"',feb='"+fy+"', march= '"+mh+"', april='"+al+"', may='"+my+"', june='"+je+"', july='"+july+"', aug='"+at+"', sep='"+sr+"', oct='"+or+"',nov='"+nr+"', decc='"+dr+"' where std_gr='"+std_gr.getText()+"'");
        } catch (Exception ex) {
            Logger.getLogger(FeesStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    public void checkstatus(String a, JComboBox b) {
        if (a.equals("Paid")) {
            b.setSelectedItem("Paid");
        } else if (a.equals("Not Paid")) {
            b.setSelectedItem("Not Paid");
        }
    }
    
    public void clearText(){
        pjan.setText("");
        pfeb.setText("");
        pmarch.setText("");
        papril.setText("");
        pmay.setText("");
        pjune.setText("");
        pjuly.setText("");
        paug.setText("");
        psep.setText("");
        poct.setText("");
        pnov.setText("");
        pdec.setText("");
        djan.setText("");
        dfeb.setText("");
        dmarch.setText("");
        dapril.setText("");
        dmay.setText("");
        djune.setText("");
        djuly.setText("");
        daug.setText("");
        dsep.setText("");
        doct.setText("");
        dnov.setText("");
        ddec.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeesStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> april1;
    private javax.swing.JComboBox<String> aug1;
    private javax.swing.JTextField dapril;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField daug;
    private javax.swing.JTextField ddec;
    private javax.swing.JComboBox<String> dec1;
    private javax.swing.JTextField dfeb;
    private javax.swing.JTextField djan;
    private javax.swing.JTextField djuly;
    private javax.swing.JTextField djune;
    private javax.swing.JTextField dmarch;
    private javax.swing.JTextField dmay;
    private javax.swing.JTextField dnov;
    private javax.swing.JTextField doct;
    private javax.swing.JTextField dsep;
    public javax.swing.JComboBox<String> feb1;
    private javax.swing.JComboBox<String> fee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> jan1;
    private javax.swing.JComboBox<String> july1;
    private javax.swing.JComboBox<String> june1;
    private javax.swing.JComboBox<String> march1;
    private javax.swing.JComboBox<String> may1;
    private javax.swing.JComboBox<String> nov1;
    private javax.swing.JComboBox<String> oct1;
    private javax.swing.JTextField papril;
    private javax.swing.JTextField paug;
    private javax.swing.JTextField pdec;
    private javax.swing.JTextField pfeb;
    private javax.swing.JTextField pjan;
    private javax.swing.JTextField pjuly;
    private javax.swing.JTextField pjune;
    private javax.swing.JTextField pmarch;
    private javax.swing.JTextField pmay;
    private javax.swing.JTextField pnov;
    private javax.swing.JTextField poct;
    private javax.swing.JTextField psep;
    private javax.swing.JLabel search;
    private javax.swing.JComboBox<String> sep1;
    public javax.swing.JTextField std_gr;
    // End of variables declaration//GEN-END:variables
}
