/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import AppPackage.AnimationClass.*;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.prompt.PromptSupport;
import sun.security.util.Password;

/**
 *
 * @author rkhan
 */
public class Login extends javax.swing.JFrame {
    PreparedStatement pst;
    ResultSet rs;
    Connection conn;
    Statement st;
   
    
    public Login() {
        setIconImage(new ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        getContentPane().setBackground(new Color(255,255,255));
        initComponents();
        PromptSupport.setPrompt("Username", user);
        PromptSupport.setPrompt("Password", pass);
        
        try {
            DatabaseConnection.getCon();
            jLabel2.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Offline_26px_1.png")));
            jLabel1.setText("Cannot Connect to Database.");
            jLabel1.setForeground(Color.red);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(627, 281));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Click Anywhere to Continue...");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 260, 210, 14);

        logo.setBackground(new java.awt.Color(0, 196, 75));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.setOpaque(true);
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoMouseReleased(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(-10, -10, 690, 310);

        jSeparator2.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator2.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(170, 160, 320, 10);

        user.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(0, 196, 75));
        user.setBorder(null);
        user.setFocusable(false);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(170, 70, 320, 30);

        pass.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        pass.setBorder(null);
        pass.setFocusable(false);
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(170, 130, 320, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator3.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(170, 100, 320, 10);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 196, 75), 2));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 196, 75));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(460, 220, 100, 40);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 196, 75));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Online_26px.png"))); // NOI18N
        jLabel1.setText("Connected!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 170, 260, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 196, 75));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sync_26px.png"))); // NOI18N
        jLabel2.setText("Retry");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 170, 70, 30);

        jLabel6.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 196, 75));
        jLabel6.setText("Login:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 20, 57, 28);

        setSize(new java.awt.Dimension(649, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user.setText("");
    }//GEN-LAST:event_userMouseClicked

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        pass.setText("");
    }//GEN-LAST:event_passMouseClicked

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
       user.setText("");
    }//GEN-LAST:event_userFocusGained

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        pass.setText("");
    }//GEN-LAST:event_passFocusGained

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        checkCred();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            checkCred();
        }
    }//GEN-LAST:event_passKeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            DatabaseConnection.getCon();
            jLabel2.setVisible(false);
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Online_26px.png")));
            jLabel1.setText("Connected!");
            jLabel1.setForeground(new Color(0,196,75));
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Offline_26px_1.png")));
            jLabel1.setText("Cannot Connect to Database.");
            jLabel1.setForeground(Color.red);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void logoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseReleased
        AnimationClass acc = new AnimationClass();
        acc.jLabelYUp(-10, -500, 7, 10, logo);
        user.setFocusable(true);
        pass.setFocusable(true);
    }//GEN-LAST:event_logoMouseReleased

    /**
     * @param args the command line arguments
     */
    
    public void checkCred(){
        String qry = "Select * from users where username=? and pass=?";
        StartGUI sg = new StartGUI();
       try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/std_registry", "root", "i4xJNmuaQYCEvPD8");
            pst = conn.prepareStatement(qry);
            pst.setString(1, user.getText());
            pst.setString(2, pass.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date date = new Date();
                String frmtdDate = dateFormat.format(date);
                String qry2 = "Insert into log values('"+user.getText()+"','"+frmtdDate+"','"+frmtdDate+"', 'Currently Logged In.')";
                DatabaseConnection.setData(qry2);
                System.out.println(qry2);
                sg.setVisible(true);
                sg.show_user.setText(user.getText());
                sg.username = user.getText();
                this.dispose();
            } else{
                StartGUI.displayMessage("Incorrect username or password.");
            }
                
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            StartGUI.displayMessage("Incorrect username or password!");
            jLabel6.setText("Login:");
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Offline_26px_1.png")));
            jLabel1.setText("Cannot Connect to Database.");
            jLabel1.setForeground(Color.red);
            jLabel2.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass;
    public javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
