/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author rkhan
 */
public class SendMail extends javax.swing.JFrame {

    /**
     * Creates new form SendMail
     */
    public SendMail() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        PromptSupport.setPrompt("Enter GR Number for email", std_gr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JTextArea();
        recipient = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        std_gr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setColumns(20);
        body.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        body.setForeground(new java.awt.Color(40, 60, 117));
        body.setRows(5);
        jScrollPane1.setViewportView(body);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 390, 220));

        recipient.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        recipient.setForeground(new java.awt.Color(0, 196, 75));
        recipient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recipientKeyReleased(evt);
            }
        });
        getContentPane().add(recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 390, 30));

        subject.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        subject.setForeground(new java.awt.Color(0, 196, 75));
        getContentPane().add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 390, 30));

        jLabel3.setFont(new java.awt.Font("Champagne & Limousines", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 196, 75));
        jLabel3.setText("Subject:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 196, 75), 2, true));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Champagne & Limousines", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 196, 75));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sent_22px.png"))); // NOI18N
        jLabel2.setText("Send");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 100, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 20, 20));

        std_gr.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        std_gr.setForeground(new java.awt.Color(0, 196, 75));
        std_gr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                std_grKeyPressed(evt);
            }
        });
        getContentPane().add(std_gr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 260, 30));

        jLabel5.setFont(new java.awt.Font("Champagne & Limousines", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 196, 75));
        jLabel5.setText("GR Number for Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_22px_1.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 30, 30));

        jLabel7.setFont(new java.awt.Font("Champagne & Limousines", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 196, 75));
        jLabel7.setText("To:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        setSize(new java.awt.Dimension(600, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Properties props = new Properties();
        String host = "smtp.gmail.com";
        String port = "465";
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", port);
        props.put("mail.smtp.socketFactory.port", port);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("danyal.ak002@gmail.com", "dantheman!$");
            }
        }
        );

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("geniusdan05@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipient.getText()));
            message.setSubject(subject.getText());
            message.setText(body.getText());
            Transport.send(message);
            StartGUI.displayMessage("Mail Sent Successfully.");
            recipient.setText("");
            body.setText("");
            subject.setText("");
            jLabel1.setIcon(null);

        } catch (Exception e) {
            Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, e);
            StartGUI.displayMessage("Mail could not be sent.");
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void recipientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recipientKeyReleased
       String get = recipient.getText();
       if(!get.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")){
           jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Delete.png")));
       }else if(get.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")){
           jLabel1.setIcon(new ImageIcon(getClass().getResource("/Images/Check.png")));
       }
        
    }//GEN-LAST:event_recipientKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        getGR();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void std_grKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_grKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            getGR();
        }
    }//GEN-LAST:event_std_grKeyPressed

    public void getGR(){
        try {
            ResultSet rs = DatabaseConnection.getData("Select * from main where std_gr='"+std_gr.getText()+"'");
            if (rs.next()) {                
              recipient.setText(rs.getString("std_email"));
            }else if(!rs.next()){
                StartGUI.displayMessage("No record found!");
            }
        } catch (Exception ex) {
            Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField recipient;
    private javax.swing.JTextField std_gr;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
