/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.StartGUI.displayMessage;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.joda.time.DateTime;
import org.joda.time.Period;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;
import org.joda.time.DateTime;
import org.joda.time.Period;

/**
 *
 * @author rkhan
 */
public class StudentFiles extends javax.swing.JFrame {
        Connection conn;
        Statement st;
        ResultSet rs = null;
        int xMouse, yMouse;
        String s;
        DialogBox db = new DialogBox();
        boolean check;
        String username,filename,ImgName;
        String dt1, dt2, calcTime;
        
        
    public StudentFiles() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/icon.png")).getImage());
        getContentPane().setBackground(new Color(255, 255, 255));
        PromptSupport.setPrompt("Enter GR here to search", gr_std);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mode = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        Container = new javax.swing.JPanel();
        std_info = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        std_age = new javax.swing.JTextField();
        std_name = new javax.swing.JTextField();
        std_class = new javax.swing.JTextField();
        std_dob = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        std_gr = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        std_rollno = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        grnumber = new javax.swing.JLabel();
        rollnumber = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        std_parentinfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        std_mcnic = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        std_religion = new javax.swing.JComboBox<>();
        jSeparator12 = new javax.swing.JSeparator();
        std_fname = new javax.swing.JTextField();
        std_fcnic = new javax.swing.JTextField();
        std_mname = new javax.swing.JTextField();
        std_ress = new javax.swing.JTextField();
        fname = new javax.swing.JLabel();
        fcnic = new javax.swing.JLabel();
        mcnic = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        std_email = new javax.swing.JTextField();
        mname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        std_contact = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        std_homephone = new javax.swing.JTextField();
        std_fjob = new javax.swing.JTextField();
        std_fjaddress = new javax.swing.JTextField();
        std_fphone = new javax.swing.JTextField();
        std_mjob = new javax.swing.JTextField();
        std_mjaddress = new javax.swing.JTextField();
        std_mphone = new javax.swing.JTextField();
        fphone = new javax.swing.JLabel();
        mphone = new javax.swing.JLabel();
        homephone = new javax.swing.JLabel();
        std_pic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mode_ro = new javax.swing.JRadioButton();
        mode_edit = new javax.swing.JRadioButton();
        gr_std = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setAutoscrolls(true);
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_info.setBackground(new java.awt.Color(255, 255, 255));
        std_info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Champagne & Limousines", 1, 16), new java.awt.Color(0, 196, 75))); // NOI18N
        std_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 196, 75));
        jLabel3.setText("Age");
        std_info.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 196, 75));
        jLabel4.setText("Full Name");
        std_info.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 196, 75));
        jLabel6.setText("Class");
        std_info.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 196, 75));
        jLabel7.setText("Date of Birth");
        std_info.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator1.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator2.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator4.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator5.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 10));

        std_age.setEditable(false);
        std_age.setBackground(new java.awt.Color(255, 255, 255));
        std_age.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        std_age.setForeground(new java.awt.Color(0, 196, 75));
        std_age.setToolTipText("Enter your age here");
        std_age.setBorder(null);
        std_info.add(std_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, -1));

        std_name.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        std_name.setForeground(new java.awt.Color(0, 196, 75));
        std_name.setToolTipText("Enter your name here");
        std_name.setBorder(null);
        std_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_nameKeyReleased(evt);
            }
        });
        std_info.add(std_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 320, -1));

        std_class.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        std_class.setForeground(new java.awt.Color(0, 196, 75));
        std_class.setToolTipText("Enter your class here");
        std_class.setBorder(null);
        std_info.add(std_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, -1));

        std_dob.setBackground(new java.awt.Color(255, 255, 255));
        std_dob.setForeground(new java.awt.Color(0, 196, 75));
        std_dob.setToolTipText("");
        std_dob.setDateFormatString("yyyy-MM-dd");
        std_dob.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        std_dob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                std_dobPropertyChange(evt);
            }
        });
        std_info.add(std_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear Symbol_24px.png"))); // NOI18N
        jLabel14.setToolTipText("Clear All Text Fields");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        std_info.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 196, 75));
        jLabel16.setText("GR. Number");
        std_info.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        std_gr.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_gr.setForeground(new java.awt.Color(0, 196, 75));
        std_gr.setToolTipText("Enter your GR Number here to search/add/delete/update");
        std_gr.setBorder(null);
        std_gr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                std_grMouseClicked(evt);
            }
        });
        std_gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_grActionPerformed(evt);
            }
        });
        std_gr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                std_grKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_grKeyReleased(evt);
            }
        });
        std_info.add(std_gr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator6.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 10));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 196, 75));
        jLabel20.setText("Roll Number");
        std_info.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        std_rollno.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        std_rollno.setForeground(new java.awt.Color(0, 196, 75));
        std_rollno.setToolTipText("");
        std_rollno.setBorder(null);
        std_rollno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_rollnoKeyReleased(evt);
            }
        });
        std_info.add(std_rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 320, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator10.setForeground(new java.awt.Color(0, 196, 75));
        std_info.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 320, 10));
        std_info.add(grnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));
        std_info.add(rollnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));
        std_info.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        Container.add(std_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 420));

        std_parentinfo.setBackground(new java.awt.Color(255, 255, 255));
        std_parentinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Parental Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Champagne & Limousines", 1, 16), new java.awt.Color(0, 196, 75))); // NOI18N
        std_parentinfo.setMinimumSize(new java.awt.Dimension(354, 340));
        std_parentinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 196, 75));
        jLabel5.setText("Father's Name");
        std_parentinfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        std_mcnic.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_mcnic.setForeground(new java.awt.Color(0, 196, 75));
        std_mcnic.setToolTipText("");
        std_mcnic.setBorder(null);
        std_mcnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_mcnicKeyReleased(evt);
            }
        });
        std_parentinfo.add(std_mcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator3.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator7.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 320, 10));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 196, 75));
        jLabel17.setText("Email");
        std_parentinfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 196, 75));
        jLabel18.setText("Father's CNIC");
        std_parentinfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator8.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator9.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 10));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 196, 75));
        jLabel19.setText("Mother's Name");
        std_parentinfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 196, 75));
        jLabel21.setText("Religion");
        std_parentinfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 196, 75));
        jLabel22.setText("Mother's CNIC");
        std_parentinfo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator11.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 10));

        std_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Christianity", "Hinduism", "Parsi" }));
        std_religion.setBorder(null);
        std_parentinfo.add(std_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, -1));

        jSeparator12.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator12.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 10));

        std_fname.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_fname.setForeground(new java.awt.Color(0, 196, 75));
        std_fname.setToolTipText("");
        std_fname.setBorder(null);
        std_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_fnameKeyReleased(evt);
            }
        });
        std_parentinfo.add(std_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, -1));

        std_fcnic.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_fcnic.setForeground(new java.awt.Color(0, 196, 75));
        std_fcnic.setToolTipText("");
        std_fcnic.setBorder(null);
        std_fcnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_fcnicKeyReleased(evt);
            }
        });
        std_parentinfo.add(std_fcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, -1));

        std_mname.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_mname.setForeground(new java.awt.Color(0, 196, 75));
        std_mname.setToolTipText("");
        std_mname.setBorder(null);
        std_mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_mnameKeyReleased(evt);
            }
        });
        std_parentinfo.add(std_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, -1));

        std_ress.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_ress.setForeground(new java.awt.Color(0, 196, 75));
        std_ress.setToolTipText("");
        std_ress.setBorder(null);
        std_parentinfo.add(std_ress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, -1));
        std_parentinfo.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        std_parentinfo.add(fcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        std_parentinfo.add(mcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 196, 75));
        jLabel30.setText("Residential Address");
        std_parentinfo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jSeparator20.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator20.setForeground(new java.awt.Color(0, 196, 75));
        std_parentinfo.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 10));

        std_email.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_email.setForeground(new java.awt.Color(0, 196, 75));
        std_email.setToolTipText("");
        std_email.setBorder(null);
        std_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_emailKeyReleased(evt);
            }
        });
        std_parentinfo.add(std_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, -1));
        std_parentinfo.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));
        std_parentinfo.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        Container.add(std_parentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 360, 420));

        std_contact.setBackground(new java.awt.Color(255, 255, 255));
        std_contact.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vocational Details & Contact", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Champagne & Limousines", 1, 16), new java.awt.Color(0, 196, 75))); // NOI18N
        std_contact.setAutoscrolls(true);
        std_contact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 196, 75));
        jLabel23.setText("Father's Occupation");
        std_contact.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator13.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 10));

        jSeparator14.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator14.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 10));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 196, 75));
        jLabel24.setText("Father's Office Address");
        std_contact.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator15.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 320, 10));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 196, 75));
        jLabel25.setText("Mother's Occupation");
        std_contact.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator16.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 10));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 196, 75));
        jLabel26.setText("Mother's Office Address");
        std_contact.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 196, 75));
        jLabel27.setText("Father's Phone Number");
        std_contact.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator17.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 10));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 196, 75));
        jLabel28.setText("Mother's Phone Number");
        std_contact.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jSeparator18.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator18.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 10));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 196, 75));
        jLabel29.setText("Residential Phone Number");
        std_contact.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jSeparator19.setBackground(new java.awt.Color(0, 196, 75));
        jSeparator19.setForeground(new java.awt.Color(0, 196, 75));
        std_contact.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 320, 10));

        std_homephone.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_homephone.setForeground(new java.awt.Color(0, 196, 75));
        std_homephone.setToolTipText("");
        std_homephone.setBorder(null);
        std_homephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_homephoneKeyReleased(evt);
            }
        });
        std_contact.add(std_homephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 300, -1));

        std_fjob.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_fjob.setForeground(new java.awt.Color(0, 196, 75));
        std_fjob.setToolTipText("");
        std_fjob.setBorder(null);
        std_contact.add(std_fjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, -1));

        std_fjaddress.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_fjaddress.setForeground(new java.awt.Color(0, 196, 75));
        std_fjaddress.setToolTipText("");
        std_fjaddress.setBorder(null);
        std_contact.add(std_fjaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, -1));

        std_fphone.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_fphone.setForeground(new java.awt.Color(0, 196, 75));
        std_fphone.setToolTipText("");
        std_fphone.setBorder(null);
        std_fphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_fphoneKeyReleased(evt);
            }
        });
        std_contact.add(std_fphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, -1));

        std_mjob.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_mjob.setForeground(new java.awt.Color(0, 196, 75));
        std_mjob.setToolTipText("");
        std_mjob.setBorder(null);
        std_contact.add(std_mjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, -1));

        std_mjaddress.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_mjaddress.setForeground(new java.awt.Color(0, 196, 75));
        std_mjaddress.setToolTipText("");
        std_mjaddress.setBorder(null);
        std_contact.add(std_mjaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, -1));

        std_mphone.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        std_mphone.setForeground(new java.awt.Color(0, 196, 75));
        std_mphone.setToolTipText("");
        std_mphone.setBorder(null);
        std_mphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                std_mphoneKeyReleased(evt);
            }
        });
        std_contact.add(std_mphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, -1));
        std_contact.add(fphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));
        std_contact.add(mphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));
        std_contact.add(homephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        Container.add(std_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 360, 420));

        jScrollPane2.setViewportView(Container);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 770, 460));

        std_pic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 196, 75), 2), "Student Picture", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Champagne & Limousines", 1, 14), new java.awt.Color(0, 196, 75))); // NOI18N
        getContentPane().add(std_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 140));

        jButton1.setText("Choose Image File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

        jButton2.setText("Upload Files");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, -1));

        jPanel1.setBackground(new java.awt.Color(0, 196, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Champagne & Limousines", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Files");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 130, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mode:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, 40));

        mode_ro.setBackground(new java.awt.Color(0, 196, 75));
        mode.add(mode_ro);
        mode_ro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mode_ro.setForeground(new java.awt.Color(255, 255, 255));
        mode_ro.setSelected(true);
        mode_ro.setText("Read-Only");
        mode_ro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mode_roPropertyChange(evt);
            }
        });
        jPanel1.add(mode_ro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, 40));

        mode_edit.setBackground(new java.awt.Color(0, 196, 75));
        mode.add(mode_edit);
        mode_edit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mode_edit.setForeground(new java.awt.Color(255, 255, 255));
        mode_edit.setText("Editable");
        mode_edit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mode_editPropertyChange(evt);
            }
        });
        jPanel1.add(mode_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        gr_std.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        gr_std.setForeground(new java.awt.Color(0, 196, 75));
        gr_std.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gr_stdKeyPressed(evt);
            }
        });
        getContentPane().add(gr_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 30));

        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_28px_2.png"))); // NOI18N
        search.setToolTipText("Search for a record");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 40, 30));

        addbtn.setText("Add");
        addbtn.setBorder(null);
        addbtn.setEnabled(false);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 70, 30));

        updatebtn.setText("Update");
        updatebtn.setBorder(null);
        updatebtn.setEnabled(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 70, 30));

        jButton3.setText("View Submiited Docs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, -1));

        jButton4.setText("Edit Fee Status");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, -1));

        jButton5.setForeground(java.awt.Color.red);
        jButton5.setText("Delete this file");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 150, -1));

        setSize(new java.awt.Dimension(1014, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void std_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_nameKeyReleased
        validateText(std_name, name);
    }//GEN-LAST:event_std_nameKeyReleased

    private void std_dobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_std_dobPropertyChange
        calcAge();
    }//GEN-LAST:event_std_dobPropertyChange

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchGR();
    }//GEN-LAST:event_searchMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        clearFields();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void std_grMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_std_grMouseClicked
        std_gr.setText("");
    }//GEN-LAST:event_std_grMouseClicked

    private void std_grKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_grKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchGR();
        }
    }//GEN-LAST:event_std_grKeyPressed

    private void std_grKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_grKeyReleased
        validateNumber(std_gr, grnumber);
    }//GEN-LAST:event_std_grKeyReleased

    private void std_rollnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_rollnoKeyReleased
        validateNumber(std_rollno, rollnumber);
    }//GEN-LAST:event_std_rollnoKeyReleased

    private void std_mcnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_mcnicKeyReleased
        validateNumber(std_mcnic, mcnic);
    }//GEN-LAST:event_std_mcnicKeyReleased

    private void std_fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_fnameKeyReleased
        validateText(std_fname, fname);
    }//GEN-LAST:event_std_fnameKeyReleased

    private void std_fcnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_fcnicKeyReleased
        validateNumber(std_fcnic, fcnic);
    }//GEN-LAST:event_std_fcnicKeyReleased

    private void std_mnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_mnameKeyReleased
        validateText(std_mname, mname);
    }//GEN-LAST:event_std_mnameKeyReleased

    private void std_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_emailKeyReleased
        String get = std_email.getText();
        if (!get.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")) {
            email.setIcon(new ImageIcon(getClass().getResource("/Images/Delete.png")));
        } else if (get.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$")) {
            email.setIcon(new ImageIcon(getClass().getResource("/Images/Check.png")));
        }
    }//GEN-LAST:event_std_emailKeyReleased

    private void std_homephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_homephoneKeyReleased
        validateNumber(std_homephone, homephone);
    }//GEN-LAST:event_std_homephoneKeyReleased

    private void std_fphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_fphoneKeyReleased
        validateNumber(std_fphone, fphone);
    }//GEN-LAST:event_std_fphoneKeyReleased

    private void std_mphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_std_mphoneKeyReleased
        validateNumber(std_mphone, mphone);
    }//GEN-LAST:event_std_mphoneKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser jf = new JFileChooser();
            int a = jf.showOpenDialog(this);

            if (a == JFileChooser.APPROVE_OPTION) {
                File f = jf.getSelectedFile();
                ImgName = jf.getSelectedFile().getName();
                ImageIcon icon = new ImageIcon(f.getPath());
                Image img1 = icon.getImage().getScaledInstance(150, 150, 150);
                ImageIcon icon1 = new ImageIcon(img1);
                std_pic.setIcon(icon1);

                FileInputStream from = new FileInputStream(f);
                FileOutputStream to = new FileOutputStream("src\\Photos\\" + ImgName);

                    byte[] buffer = new byte[4024];

                    int bytread;

                    while ((bytread = from.read(buffer)) != -1) {
                        to.write(buffer);
                    }
                    from.close();
                    to.close();

                }
            } catch (Exception ex) {
                displayMessage("No Data!");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        int a = chooser.showOpenDialog(std_info);

        if (a == JFileChooser.APPROVE_OPTION) {
            FileOutputStream to = null;
            try {
                File f = chooser.getSelectedFile();
                //String filelocation = f.getAbsolutePath();
                filename = f.getName();
                FileInputStream from = new FileInputStream(f);
                to = new FileOutputStream("src\\Files\\" + filename);
                    byte[] buffer = new byte[4024];
                    int bytread;
                    while ((bytread = from.read(buffer)) != -1) {
                        to.write(buffer);
                    }   from.close();
                    to.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        to.close();
                    } catch (IOException ex) {
                        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void std_grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_grActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_grActionPerformed

    private void gr_stdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gr_stdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchGR();
        }
    }//GEN-LAST:event_gr_stdKeyPressed

    private void mode_roPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mode_roPropertyChange
        if(mode_ro.isSelected()){
            addbtn.setEnabled(false);
            updatebtn.setEnabled(false);
        }else if(mode_edit.isSelected()){
            addbtn.setEnabled(true);
            updatebtn.setEnabled(true);
        }
    }//GEN-LAST:event_mode_roPropertyChange

    private void mode_editPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mode_editPropertyChange
         if(mode_ro.isSelected()){
            addbtn.setEnabled(false);
            updatebtn.setEnabled(false);
        }else if(mode_edit.isSelected()){
            addbtn.setEnabled(true);
            updatebtn.setEnabled(true);
        }
    }//GEN-LAST:event_mode_editPropertyChange

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String gr = std_gr.getText();
        String clss = std_class.getText();
        String age = std_age.getText();
        String name = std_name.getText();
        String rollno = std_rollno.getText();
        String fname = std_fname.getText();
        String fcncic = std_fcnic.getText();
        String mname = std_mname.getText();
        String mcnic = std_mcnic.getText();
        String ress = std_ress.getText();
        String fjob = std_fjob.getText();
        String fjaddress = std_fjaddress.getText();
        String fphone = std_fphone.getText();
        String mjob = std_mjob.getText();
        String mjaddress = std_mjaddress.getText();
        String mphone = std_mphone.getText();
        String homephone = std_homephone.getText();
        String religion = std_religion.getSelectedItem().toString();
        String email = std_email.getText();
        SimpleDateFormat ab = new SimpleDateFormat("yyyy-MM-dd");
        String dob = ab.format(std_dob.getDate());
        
        

        try {
            String qry1 = "insert into main values('" + name + "','" + gr + "','" + clss + "','" + dob + "','" + age + "','" + rollno + "','" + fname + "','" + fcncic + "','" + mname + "','" + mcnic + "','" + ress + "','" + fjob + "','" + fjaddress + "','" + fphone + "','" + mjob + "','" + mjaddress + "','" + mphone + "','" + homephone + "','" + email + "','" + religion + "','" + ImgName + "')";
            int a = DatabaseConnection.setData(qry1);

            String qry2 = "Insert into fee_status values('" + gr + "','" + name + "','" + clss + "','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid','Not Paid')";
            String qry3 = "insert into pay_order values('" + gr + "','0','0','0','0','0','0','0','0','0','0','0','0')";
            String qry4 = "insert into timestamp values('" + gr + "',0,0,0,0,0,0,0,0,0,0,0,0)";
            
            conn = DatabaseConnection.getCon();
            Statement st = conn.createStatement();
            st.addBatch(qry2);
            st.addBatch(qry3);
            st.addBatch(qry4);
            st.executeBatch();

            if (a > 0) {
                displayMessage("Record added successfully.");
                clearFields();
                clearLabels();
            } else {
                displayMessage("Record not added.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            int MYSQL_DUPLICATE_PK = 1062;
            if (ex.getErrorCode() == MYSQL_DUPLICATE_PK) {
                displayMessage("GR Number already exists.");
            }
        } catch (Exception ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        String gr = std_gr.getText();
        String clss = std_class.getText();
        String age = std_age.getText();
        String name = std_name.getText();
        String rollno = std_rollno.getText();
        String fname = std_fname.getText();
        String fcncic = std_fcnic.getText();
        String mname = std_mname.getText();
        String mcnic = std_mcnic.getText();
        String ress = std_ress.getText();
        String fjob = std_fjob.getText();
        String fjaddress = std_fjaddress.getText();
        String fphone = std_fphone.getText();
        String mjob = std_mjob.getText();
        String mjaddress = std_mjaddress.getText();
        String mphone = std_mphone.getText();
        String homephone = std_homephone.getText();
        String religion = std_religion.getSelectedItem().toString();
        String email = std_email.getText();
        SimpleDateFormat ab = new SimpleDateFormat("yyyy-MM-dd");
        String dob = ab.format(std_dob.getDate());
        Date date = new Date();
        String date1 = ab.format(date);

        try {
            String qry1= "Insert into applications values('"+gr+"','"+date1+"','"+filename+"')";
            String qry = "update main set std_name='" + name + "',std_class='" + clss + "',std_dob='" + dob + "',std_age='" + age + "',std_rollno='" + rollno + "',std_fname='" + fname + "',std_fcnic='" + fcncic + "',std_mname='" + mname + "',std_mcnic='" + mcnic + "',std_haddress='" + ress + "',std_fjob='" + fjob + "',std_fjaddress='" + fjaddress + "',std_fphone='" + fphone + "',std_mjob='" + mjob + "',std_mjaddress='" + mjaddress + "',std_mphone='" + mphone + "',std_homephone='" + homephone + "',std_email='" + email + "',std_religion = '" + religion + "',std_pic='" + ImgName + "' where std_gr = '" + std_gr.getText() + "'";
            String qry3 = "update fee_status set std_class= '"+clss+"' where std_gr='"+gr+"'";
            int a = DatabaseConnection.setData(qry);
            DatabaseConnection.setData(qry1);
            DatabaseConnection.setData(qry3);
            if (a > 0) {

                displayMessage("Record updated successfully.");
                clearFields();
                clearLabels();

            } else {

                displayMessage("Record updation failed.");

            }

        } catch (SQLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            int MYSQL_DUPLICATE_PK = 1062;
            if (ex.getErrorCode() == MYSQL_DUPLICATE_PK) {
                displayMessage("GR Number already exists");
            }

            if (std_age.getText().length() > 2) {
                displayMessage("Please enter valid age");
            } else if (dob.matches("([0-9]{4})/([0-9]{2})/([0-9]{2})")) {

            } else {
                displayMessage("Incorrect date format! or type");
            }
        } catch (Exception ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Applications ap = new Applications();
        ap.setAlwaysOnTop(true);
        ap.setVisible(true);
        String gnum = std_gr.getText();
        ap.std_gr.setText(gnum);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FeesStatus fs = new FeesStatus();
        fs.setVisible(true);
        fs.setAlwaysOnTop(true);
        String text = std_gr.getText();
        fs.std_gr.setText(text);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String qry = "delete from main where std_gr = '" + std_gr.getText() + "'";
            String qry2 = "delete from applications where std_gr = '" + std_gr.getText() + "'";
            String qry3 = "delete from fee_status where std_gr = '" + std_gr.getText() + "'";
            String qry4 = "delete from pay_order where std_gr = '" + std_gr.getText() + "'";
            String qry5 = "delete from timestamp where std_gr = '" + std_gr.getText() + "'";
            
            conn = DatabaseConnection.getCon();
            Statement st = conn.createStatement();
            st.addBatch(qry2);
            st.addBatch(qry3);
            st.addBatch(qry4);
            st.addBatch(qry5);
            st.executeBatch();
           
            int a = DatabaseConnection.setData(qry);
            if (a > 0) {

                displayMessage("Record deleted successfully.");
                clearFields();

            } else {
                displayMessage("Record Deletion Failed");

            }
        } catch (SQLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);

        } catch (Exception ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
    public void validateText(JTextField st, JLabel label) {
        String validate = st.getText();
        if (!validate.matches("^[a-z\\s\\s\\sA-Z]+$")) {
            label.setIcon(new ImageIcon(getClass().getResource("/Images/Delete.png")));
            check = false;
        } else if (validate.matches("^[a-z\\s\\s\\sA-Z]+$")) {
            label.setIcon(new ImageIcon(getClass().getResource("/Images/Check.png")));
            check = true;
        }

    }

    public void validateNumber(JTextField st, JLabel label) {
        String validate = st.getText();
        if (!validate.matches("[0-9]+")) {
            label.setIcon(new ImageIcon(getClass().getResource("/Images/Delete.png")));
            check = false;
        } else if (validate.matches("[0-9]+")) {
            label.setIcon(new ImageIcon(getClass().getResource("/Images/Check.png")));
            check = true;
        }
    }

    public ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(std_pic.getWidth(), std_pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    public static void displayMessage(String s) {
        DialogBox db = new DialogBox();
        db.jTextField1.setText(s);
        db.setVisible(true);
        db.setAlwaysOnTop(true);
    }

    public void clearFields() {
        std_gr.setText("");
        std_name.setText("");
        std_age.setText("");
        std_class.setText("");
        std_rollno.setText("");
        std_fname.setText("");
        std_fcnic.setText("");
        std_mname.setText("");
        std_mcnic.setText("");
        std_ress.setText("");
        std_fjob.setText("");
        std_fjaddress.setText("");
        std_fphone.setText("");
        std_mjob.setText("");
        std_mjaddress.setText("");
        std_mphone.setText("");
        std_homephone.setText("");
        std_religion.setSelectedItem("Islam");
        std_dob.setDate(new Date());
        std_pic.setIcon(null);
    }

    public void clearLabels() {
        grnumber.setIcon(null);
        rollnumber.setIcon(null);
        name.setIcon(null);
        fname.setIcon(null);
        mname.setIcon(null);
        fcnic.setIcon(null);
        mcnic.setIcon(null);
        fphone.setIcon(null);
        mphone.setIcon(null);
        homephone.setIcon(null);
    }

    public void calcAge() {
        DateTime birthDate = new DateTime(std_dob.getDate());
        DateTime now = new DateTime();
        Period period = new Period(birthDate, now);
        int years = period.getYears();
        std_age.setText(Integer.toString(years));
    }
    
    public void searchGR() {
        String clss = std_class.getText();
        try {
            String qry = "SELECT * FROM main WHERE std_gr='" + gr_std.getText() + "'";
            ResultSet rs = DatabaseConnection.getData(qry);
            if (!rs.next()) {
                displayMessage("No record found!");
            }
            if (rs.first()) {
                std_gr.setText(gr_std.getText());
                std_name.setText(rs.getString("std_name"));
                std_class.setText(rs.getString("std_class"));
                std_age.setText(rs.getString("std_age"));
                std_rollno.setText(rs.getString("std_rollno"));
                std_fname.setText(rs.getString("std_fname"));
                std_fcnic.setText(rs.getString("std_fcnic"));
                std_mname.setText(rs.getString("std_mname"));
                std_mcnic.setText(rs.getString("std_mcnic"));
                std_ress.setText(rs.getString("std_haddress"));
                std_fjob.setText(rs.getString("std_fjob"));
                std_fjaddress.setText(rs.getString("std_fjaddress"));
                std_fphone.setText(rs.getString("std_fphone"));
                std_mjob.setText(rs.getString("std_mjob"));
                std_mjaddress.setText(rs.getString("std_mjaddress"));
                std_mphone.setText(rs.getString("std_mphone"));
                std_homephone.setText(rs.getString("std_homephone"));
                std_religion.setSelectedItem(rs.getString("std_religion"));
                std_email.setText(rs.getString("std_email"));
                ImageIcon abc = new ImageIcon("src//Photos//" + rs.getString("std_pic"));
                Image img1 = abc.getImage().getScaledInstance(150, 150, 150);
                ImageIcon icon1 = new ImageIcon(img1);
                std_pic.setIcon(icon1);

                String datevalue = rs.getString("std_dob");
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                std_dob.setDate(date);
            }
        } catch (Exception ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void timeDiff() {
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
            Date d2;
            Date d1;
            d2 = df.parse(dt2);
            d1 = df.parse(dt1);
            long diff = Math.abs(d1.getTime() - d2.getTime());

            calcTime = String.format("%d hr, %d min, %d sec",
                    TimeUnit.MILLISECONDS.toHours(diff),
                    TimeUnit.MILLISECONDS.toMinutes(diff),
                    TimeUnit.MILLISECONDS.toSeconds(diff)
                    - TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes(diff))
            );
            System.out.println(calcTime);

        } catch (ParseException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fcnic;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel fphone;
    private javax.swing.JTextField gr_std;
    private javax.swing.JLabel grnumber;
    private javax.swing.JLabel homephone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel mcnic;
    private javax.swing.JLabel mname;
    private javax.swing.ButtonGroup mode;
    private javax.swing.JRadioButton mode_edit;
    private javax.swing.JRadioButton mode_ro;
    private javax.swing.JLabel mphone;
    private javax.swing.JLabel name;
    private javax.swing.JLabel rollnumber;
    private javax.swing.JLabel search;
    private javax.swing.JTextField std_age;
    public javax.swing.JTextField std_class;
    private javax.swing.JPanel std_contact;
    private com.toedter.calendar.JDateChooser std_dob;
    public javax.swing.JTextField std_email;
    public javax.swing.JTextField std_fcnic;
    public javax.swing.JTextField std_fjaddress;
    public javax.swing.JTextField std_fjob;
    public javax.swing.JTextField std_fname;
    public javax.swing.JTextField std_fphone;
    public javax.swing.JTextField std_gr;
    public javax.swing.JTextField std_homephone;
    private javax.swing.JPanel std_info;
    public javax.swing.JTextField std_mcnic;
    public javax.swing.JTextField std_mjaddress;
    public javax.swing.JTextField std_mjob;
    public javax.swing.JTextField std_mname;
    public javax.swing.JTextField std_mphone;
    public javax.swing.JTextField std_name;
    private javax.swing.JPanel std_parentinfo;
    private javax.swing.JLabel std_pic;
    private javax.swing.JComboBox<String> std_religion;
    public javax.swing.JTextField std_ress;
    public javax.swing.JTextField std_rollno;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
